### ISSUE TITLE
ConnectionRefusedError 111 to mysql  

### ISSUE THREAD

**Issue by votientu** [mrhappyasthma/Rule1-StockScreener#6]
Hi, 

I run python3 populate_database.py and get an error related to mysql. I don’t know if I have to setup mysql before ?

> Connecting to database...
Traceback (most recent call last):
  File "/home/vo/.local/lib/python3.8/site-packages/mysql/connector/network.py", line 509, in open_connection
    self.sock.connect(sockaddr)
ConnectionRefusedError: [Errno 111] Connection refused
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "populate_database.py", line 135, in <module>
    mydb = connectToMySQLUsingRootLogin()
  File "populate_database.py", line 65, in connectToMySQLUsingRootLogin
    mydb = sql.connect(
  File "/home/vo/.local/lib/python3.8/site-packages/mysql/connector/__init__.py", line 179, in connect
    return MySQLConnection(*args, **kwargs)
  File "/home/vo/.local/lib/python3.8/site-packages/mysql/connector/connection.py", line 95, in __init__
    self.connect(**kwargs)
  File "/home/vo/.local/lib/python3.8/site-packages/mysql/connector/abstracts.py", line 716, in connect
    self._open_connection()
  File "/home/vo/.local/lib/python3.8/site-packages/mysql/connector/connection.py", line 206, in _open_connection
    self._socket.open_connection()
  File "/home/vo/.local/lib/python3.8/site-packages/mysql/connector/network.py", line 511, in open_connection
    raise errors.InterfaceError(
mysql.connector.errors.InterfaceError: 2003: Can't connect to MySQL server on 'localhost:3306' (111 Connection refused)`

The IsThisStockGood is deployed on a localhost but not in production site.

Thank for your effort in the project :)

**Comment by mrhappyasthma** [comment]
So this repo doesn't actually require the IsThisStockGood website running. It just calls into the underlying python calls to scrape the data without needing the web UI at all.

You will need to set up mysql, however. 

The script attempts to connect with:

```
  mydb = sql.connect(
    host="localhost",
    user="root",
    password="root",
  )
```

You'll need to make sure that `mysql` is installed and that you update this code in `populate_database.py` if you used a different username or password on your install.

you can install MySQL here: https://dev.mysql.com/downloads/installer/

I added more info to the readme for posterity: https://github.com/mrhappyasthma/Rule1-StockScreener/commit/f088f13bdeda3e089464cd6c958d91774ab77e32
